server:
  port: 8080

spring:
  application:
    name: tap-cdc

# Tap CDC custom configuration
tap:
  # Elasticsearch Configuration  
  elasticsearch:
    config-file: elasticsearch.yml
    host: localhost
    port: 9200
    username: elastic
    password: Cdn1dG_aV*pyDxEx7ERT
    bulk-size: 1000
    bulk-flush-interval-seconds: 5
    bulk-threads: 2

  # KingBase Configuration (optional)
  kingbase:
    config-file: kingbase.yml
    enabled: true
    sql-sync-enabled: true
    host: localhost
    port: 54321
    database: TEST
    username: SYSTEM
    password: 123456
    schema: PUBLIC
    driver-class-name: com.kingbase8.Driver
    url: ""
    sql-sync-cron: "0 0 0/1 * * ?"
    statement-parallelism: 4
    default-chunk-size: 0
    default-fetch-size: 1000
    sync-state-table: kingbase_sync_state
    sql-statements-file: classpath:sql-statements.yml
    sql-statement-groups:
      - name: large-orders
        file: classpath:sql-statements-large.yml
        cron: "0 0 * * * *"

  # Debezium Configuration
  debezium:
    server-name: tapdata-cdc
    # Tables to monitor (comma separated)
    table-include-list: public.*
    # Snapshot mode: initial, never, initial_only
    snapshot-mode: initial
    # Plugin name for PostgreSQL
    plugin-name: pgoutput
    # Offset storage (for development, use file storage)
    offset-storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
    offset-storage-file: ./offsets.dat

# Logging Configuration
logging:
  level:
    com.tapdata.cdc: DEBUG
    io.debezium: INFO
    co.elastic: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
